# PlayerArchetypes.py
# Define player archetypes

ARCHETYPES={
    "facilitator": {
        "name": "Facilitator",
        "description":"Pass first player that sets up teammates for scoring opportunities",
        "valid_positions": ["PG", "SG"],
        "stat_tendencies": {},
        "rating_floors": {},
        "rating_ceilings": {},
        "development_weights": {},
    },
    "sniper": {
        "name": "Sniper",
        "description":"Elite shooter",
        "valid_positions": ["PG", "SG", "SF", "PF", "C"],
        "stat_tendencies": {},
        "rating_floors": {},
        "rating_ceilings": {},
        "development_weights": {},
    },
    "slasher": {
        "name": "Slasher",
        "description":"Aggressive finisher around the rim",
        "valid_positions": ["PG", "SG", "SF", "PF", "C"],
        "stat_tendencies": {},
        "rating_floors": {},
        "rating_ceilings": {},
        "development_weights": {},
    },
    "lockdown_defender": {
        "name": "Lockdown Defender",
        "description": "Defensive specialist that can guard multiple positions",
        "valid_positions": ["PG", "SG", "SF", "PF", "C"],
        "stat_tendencies": {},
        "rating_floors": {},
        "rating_ceilings": {},
        "development_weights": {},
    },
    "3_and_d": {
        "name": "3 And D",
        "description":"Player that can shoot from outside and play solid defense",
        "valid_positions": ["PG", "SG", "SF"],
        "stat_tendencies": {},
        "rating_floors": {},
        "rating_ceilings": {},
        "development_weights": {},
    },
    "rebounder": {
        "name": "Rebounder",
        "description":"Player that excels at grabbing rebounds and controlling the boards",
        "valid_positions": ["PF", "C"],
        "stat_tendencies": {},
        "rating_floors": {},
        "rating_ceilings": {},
        "development_weights": {},
    },
    "rim_protector": {
        "name": "Rim Protector",
        "description": "Player that excels at blocking shots and protecting the rim",
        "valid_positions": {"PF", "C"},
        "stat_tendencies": {},
        "rating_floors": {},
        "rating_ceilings": {},
        "development_weights": {}
    },
    "all_around": {
        "name": "All Around",
        "description":"Well-rounded player that contributes in multiple areas",
        "valid_positions": ["PG", "SG", "SF", "PF", "C"],
        "stat_tendencies": {},
        "rating_floors": {},
        "rating_ceilings": {},
        "development_weights": {},
    },
    "post_scorer": {
        "name": "Post Scorer",
        "description":"Player that excels at scoring in the post and around the basket",
        "valid_positions": ["SF", "PF", "C"],
        "stat_tendencies": {},
        "rating_floors": {},
        "rating_ceilings": {},
        "development_weights": {},
    },
    "stretch_big": {
        "name": "Stretch Big",
        "description":"Big man that can shoot from outside and stretch the floor",
        "valid_positions": ["PF", "C"],
        "stat_tendencies": {},
        "rating_floors": {},
        "rating_ceilings": {},
        "development_weights": {},
    },
    "shot_creator": {
    "name": "Shot Creator",
        "description":"Player that can create their own shot and score in isolation situations",
        "valid_positions": ["PG", "SG", "SF", "PF", "C"],
        "stat_tendencies": {},
        "rating_floors": {},
        "rating_ceilings": {},
        "development_weights": {},
    },
    "elite_athlete": {
        "name": "Elite Athlete",
        "description":"Raw athleticism and physical tools that could translate to elite play",
        "valid_positions": ["PG", "SG", "SF", "PF", "C"],
        "stat_tendencies": {},
        "rating_floors": {},
        "rating_ceilings": {},
        "development_weights": {},
    },
    "paint_beast": {
        "name": "Paint Beast",
        "description":"Purely dominant force in the paint",
        "valid_positions": ["PF", "C"],
        "stat_tendencies": {},
        "rating_floors": {},
        "rating_ceilings": {},
        "development_weights": {},
    }
}